
# Practica de Laboratorio #1

## Nombre y Apellidos: José Santiago Sacón Yanchaguano

## Fecha: 22/10/2021

## Titulo
Instalación de Software para Practicas y Tutorial Python para Procesamiento de Señales

## Resumen

Esta práctica consiste en la instalación del software con la que se trabajará el presente curso y una pequeña introducción a Python.





## Ejercicios







### 1. Python básico.






In [3]:
import numpy as np

Importamos la librería Numpy para poder utilizarla en lo que requeramos.

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


Lo que se muestra en pantalla es la construcción de un arreglo simple utilizando la librería Numpy.

In [6]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


En la presente sección se construyó un nuevo arreglo esta vez de una dimensión mayor al primero mostrado.

In [8]:
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

308.2098960876465
63.79294395446777


La presente sección nos muestra la efectividad de la librería Numpy para construir y operar arreglos, esta vez añadiendo una variable para cambiar el tamaño del mismo.